name: Generate Changelog

on:
  push:
    tags:
      - "v*"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      # Kodu Checkout Et
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Tüm geçmişi ve dalları getir

      # Node.js Kurulumu
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Conventional Changelog Kurulumu
      - name: Install Conventional Changelog
        run: npm install -g conventional-changelog-cli

      # Changelog Oluşturma
      - name: Generate Changelog
        run: conventional-changelog -p go -i CHANGELOG.md -s

      # Değişiklikleri Commit Et ve Pushla
      - name: Commit and Push Changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push origin HEAD:$(echo $GITHUB_REF | sed 's/refs\/tags\///')
