name: Generate Changelog

on:
  push:
    tags:
      - "v*"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Conventional Changelog
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: conventional-changelog -p go -i CHANGELOG.md -s

      - name: Commit and Push Changelog
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push
