name: Go Test

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest # You can specify other runners like windows-latest or macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the repository

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20" # Use the appropriate Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Run tests
        run: go test ./... -v # Run the Go tests with verbose output
